default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: "localhost"
  username: ""
  password: ""


development:
  <<: *default
  database: jet_development

test:
  <<: *default
  database: jet_test

production:
  <<: *default
  database: jet_production
